services:
  doge-local-dev-environment:
    container_name: doge-local-dev-environment
    # NOTE: These options keep the container open for development
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: ./dev-env
      args:
        GIT_USER_NAME: "{GIT_USER_NAME}"
        GIT_USER_EMAIL: "{GIT_USER_EMAIL}"
